.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. magmelldollar_qt test_magmelldollar_qt
clean: FORCE
	$(MAKE) -C .. magmelldollar_qt_clean test_magmelldollar_qt_clean
check: FORCE
	$(MAKE) -C .. test_magmelldollar_qt_check
magmelldollar-qt magmelldollar-qt.exe: FORCE
	 $(MAKE) -C .. magmelldollar_qt
